# Configure a default setup of Home Assistant.
# (Includes frontend, api, etc.)
default_config:

homeassistant:
  customize: !include customize.yaml

# =============================================================================
# Custom Configuration 

# Authentication
auth_providers:
  - type: homeassistant
  - type: trusted_networks
    trusted_networks:
      - 192.168.0.0/24
      - 127.0.0.1

# HTTP Configuration
http:
  use_x_forwarded_for: true
  trusted_proxies:
  - 192.168.88.0/24

# History View Configuration
history:

# Recorder Configuration
recorder:
  db_url: !secret recorder_db_url
  purge_keep_days: 14

# Speedtest
speedtestdotnet:
  monitored_conditions:
    - ping
    - download
    - upload

# Text-to-Speech
tts:
  - platform: google_translate

# Wake On LAN Support
wake_on_lan:
  broadcast_address: '255.255.255.0'

# =============================================================================
# Includes

light: !include configs/lights.yaml
script: !include_dir_merge_named configs/scripts
scene: !include configs/scenes.yaml
