# Configure a default setup of Home Assistant.
# (Includes frontend, api, etc.)
default_config:

homeassistant:
  auth_providers:
    - type: homeassistant
    - type: trusted_networks
      trusted_networks:
        - 192.168.0.0/24
        - 127.0.0.1
  customize: !include customize.yaml

# =============================================================================
# Custom Configuration 

# HTTP Configuration
http:
  use_x_forwarded_for: true
  trusted_proxies:
  - 192.168.88.0/24

# History View Configuration
history:

# InfluxDB Integration
influxdb:
  host: a0d7b954-influxdb
  port: 8086
  database: homeassistant
  username: homeassistant
  password: !secret influxdb_password
  max_retries: 3
  default_measurement: state

# MQTT Broker Configuration
mqtt:
  broker: 192.168.88.69

# Proximity Configuration (for the Tesla)
proximity:
  home_tesla:
    zone: home
    devices:
      - device_tracker.tesla_location
    tolerance: 10
    unit_of_measurement: mi

# Recorder Configuration
recorder:
  db_url: !secret recorder_db_url
  purge_keep_days: 14

# Speedtest
speedtestdotnet:
  monitored_conditions:
    - ping
    - download
    - upload

# Text-to-Speech
tts:
  - platform: google_translate

# Wake On LAN Support
wake_on_lan:
  broadcast_address: '255.255.255.0'

# =============================================================================
# Includes

automation: !include configs/automations.yaml
light: !include configs/lights.yaml
script: !include configs/scripts.yaml
scene: !include configs/scenes.yaml
sensor: !include_dir_merge_list configs/sensors/
