- alias: Update Tesla location as MQTT location updates
  initial_state: on
  trigger:
    - platform: mqtt
      topic: teslamate/cars/1/latitude
    - platform: mqtt
      topic: teslamate/cars/1/longitude
  action:
    - service: device_tracker.see
      data_template:
        dev_id: tesla_location
        gps:
          [
            "{{ states.sensor.tesla_latitude.state }}",
            "{{ states.sensor.tesla_longitude.state }}",
          ]

- alias: Turn on LG C1
  trigger:
    - platform: webostv.turn_on
      entity_id: media_player.lg_c1
  action:
    - service: wake_on_lan.send_magic_packet
      data:
        mac: !secret mac_address_lg_c1