# LIFX Lighting Control
set_studio_lights_to_bias:
  alias: Set Studio Lights to Bias
  sequence:
    - scene: scene.bias
  mode: single
set_studio_lights_to_focus:
  alias: Set Studio Lights to Focus
  sequence:
    - scene: scene.focus
  mode: single
set_studio_lights_to_intense:
  alias: Set Studio Lights to Intense
  sequence:
    - scene: scene.intense
  mode: single

# LG C1 OLED Control
switch_lgc1_off:
  alias: Power Off LG C1
  sequence:
    - service: media_player.turn_off
      entity_id: media_player.lg_c1
switch_lgc1_on:
  alias: Power On LG C1
  sequence:
    - service: media_player.turn_on
      entity_id: media_player.lg_c1
switch_lgc1_to_extron:
  alias: Switch LG C1 to Extron
  sequence:
    - service: media_player.select_source
      data:
        source: Extron
      target:
        device_id: 81b76b7173f6fead5afc04f1713eac21
  mode: single
  icon: mdi:television
switch_lgc1_to_pc:
  alias: Switch LG C1 to PC
  sequence:
    - service: media_player.select_source
      data:
        source: PC
      target:
        device_id: 81b76b7173f6fead5afc04f1713eac21
  mode: single
switch_lgc1_to_vrroom:
  alias: Switch LG C1 to VRRoom
  sequence:
    - service: media_player.select_source
      data:
        source: HDMI 2
      target:
        device_id: 81b76b7173f6fead5afc04f1713eac21
  mode: single

# HDFury VRRoom Control
vrroom_hotplug:
  alias: Trigger VRRoom Hotplug
  sequence:
  - service: rest_command.vrroom_hotplug
  mode: single
vrroom_reboot:
  alias: Trigger VRRoom Reboot
  sequence:
  - service: rest_command.vrroom_reboot
  mode: single
vrroom_rx0:
  alias: Switch VRRoom to RX0
  sequence:
  - service: rest_command.vrroom_rx0
  mode: single
vrroom_rx1:
  alias: Switch VRRoom to RX1
  sequence:
  - service: rest_command.vrroom_rx1
  mode: single
vrroom_rx2:
  alias: Switch VRRoom to RX2
  sequence:
  - service: rest_command.vrroom_rx2
  mode: single
vrroom_rx3:
  alias: Switch VRRoom to RX3
  sequence:
  - service: rest_command.vrroom_rx3
  mode: single
